### ISSUE TITLE
需要输入一些东西才可以使用功能键

### ISSUE THREAD

**Issue by UnrilWever** [fantasticit/wipi#101]
### MD编辑器需要输入一些东西，上面的功能键才能使用：
![image](https://user-images.githubusercontent.com/75024633/199686440-09bca397-7e1e-4881-8931-41efe8aae5b6.png)
### 否则会报类似 editor 是  null 的错误：
![image](https://user-images.githubusercontent.com/75024633/199686631-7dbafd76-8267-476b-8d26-71ad2dae7f39.png)

**Comment by fantasticit** [comment]
我看你提了个 PR。

**Comment by aidoit** [comment]
+1
图片实际已上传成功（在文件管理中可以看到），但会同时出现“上传成功”和“上传错误”，而且没有markdown代码插入到编辑器中。
