### ISSUE TITLE
github OAuth 登录 返回404

### ISSUE THREAD

**Issue by aidoit** [fantasticit/wipi#104]
本地构建后上传，按https://www.ruanyifeng.com/blog/2019/04/github-oauth.html 获取客户端 ID（client ID）和客户端密钥（client secret）登录返回404
![截图 2022-11-16 16-31-59](https://user-images.githubusercontent.com/22998237/202129465-a651579c-514f-4440-a2ff-01417b7aebed.png)

**Comment by fantasticit** [comment]
检查下你的地址是否正确，可通过 https://blog.codingit.cn/ 测试下我部署的。

**Comment by aidoit** [comment]
看到404我第一次时间也是以为地址有问题，因为组件源码那里没做过任何修改，地址是没问题的。

**Comment by fantasticit** [comment]
给我发邮件看下你的 github 相关配置，可以把密钥什么的打上马赛克。

**Comment by aidoit** [comment]
哪部分配置？注册oAuth那里吗？

fantasticit ***@***.***> 于2022年11月25日周五 10:48写道：

**Comment by fantasticit** [comment]
是的

**Comment by aidoit** [comment]
那个注册信息找不到了，我刚打开一个新的看了以下，意识到应该是我的回调地址错了，app地址是www.example.com，回调地址也写了www.example.com，是不是因为这个导致的404？

**Comment by fantasticit** [comment]
是的
