### ISSUE TITLE
服务端代码本地报错

### ISSUE THREAD

**Issue by kaiwenxiao** [fantasticit/wipi#105]
![image](https://user-images.githubusercontent.com/31737119/210177549-99674356-3072-4734-8d49-b11cbb6e1aa5.png)
好像是国际化的问题

![image](https://user-images.githubusercontent.com/31737119/210177562-1b2680a9-91b9-4b6e-825c-e7b65d6bb6be.png)
前端也ba报错了

**Comment by aidoit** [comment]
像是数据库编码问题

**Comment by fantasticit** [comment]
```
CREATE DATABASE  `wipi` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```
