### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Giancarlo-Ma** [fantasticit/wipi#36]
管理后台不需要登录就能访问dashboard

**Comment by fantasticit** [comment]
因为部分 api 接口是公开的，所以没有检测到 401/403。后续改下后台强制登录。

**Comment by Giancarlo-Ma** [comment]
是怎么解决monaco editor引入全局css与css module冲突的问题的

**Comment by fantasticit** [comment]
项目中使用的都是 css-modules。没有碰到冲突问题，不知道你遇到的场景是什么样的？

**Comment by Giancarlo-Ma** [comment]
项目中`import('monaco-editor/esm/vs/editor/editor.api.js'`在node_modules中引入了css文件，被next认为是全局引入了css，在`next@10.0.7`报错`Global CSS cannot be imported from within node_modules.`参考了`https://dev.to/swyx/how-to-add-monaco-editor-to-a-next-js-app-ha3`的方案，但是行不通。

**Comment by fantasticit** [comment]
这个项目的 `next` 版本是 `9.2.1` , `monaco-editor` 是 `0.20.0` ，通过 `monaco-editor/esm/vs/editor/editor.api.js` 路径引入没有你说的这个问题。

**Comment by fantasticit** [comment]
已经发现是 monaco-editor 版本问题，目前已将 monaco-editor 版本锁在 `0.20.0`。
