### ISSUE TITLE
为什么要server依赖同时安装"bcrypt": "^3.0.7",  "bcryptjs": "^2.4.3"

### ISSUE THREAD

**Issue by iolh** [fantasticit/wipi#37]
您好，打扰一下，就是我在启动项目前安装依赖的时候报了个错，主要是bcrypt安装的一点问题，我将bcrypt去除，yarn安装成功。bcrypt是c++编写的，bcryptjs是js编写的，功能相同，性能bcrypt会好些，项目里也只是使用了bcryptjs，为何还需要安装bcrypt呢，不是二者存其一即可吗?

**Comment by fantasticit** [comment]
![image](https://user-images.githubusercontent.com/26452939/110064585-5345e780-7da8-11eb-9521-792b1de3c545.png)
之前有人反馈 bcrypt 安装不上，我就切到了 bcryptjs，后续忘了 remove bcrypt 依赖。我的问题，感谢提出。
