### ISSUE TITLE
建议增加文章批量删除、批量编辑，如（更改类型，打标签，标记为new，原创等）

### ISSUE THREAD

**Issue by lm356536** [fantasticit/wipi#44]

**Comment by fantasticit** [comment]
标记为 new、原创等是怎样一个属性？（其他的可以做）

**Comment by lm356536** [comment]
以下下文章不限于技术
比如：文章的新鲜度（new，old），文章的难度（初级，普通，困难），文章的要求度（了解、熟悉、熟练掌握、精通），文章版权（原创，转载）。

**Comment by lm356536** [comment]
以下文章不限于技术
比如：文章的新鲜度（new、hot、 old），文章的难度（初级、普通、困难），文章的要求度（了解、熟悉、熟练掌握、精通），文章版权（原创、转载）。

**Comment by fantasticit** [comment]
有没有类似网站，我去看看（抄抄作业）

发自我的iPhone

**Comment by lm356536** [comment]
> 有没有类似网站，我去看看（抄抄作业） 发自我的iPhone
> […](#)
> 在 2021年4月18日，上午12:00，Lm2088 ***@***.***> 写道： ﻿ 以下下文章不限于技术 比如：文章的新鲜度（new，old），文章的难度（初级，普通，困难），文章的要求度（了解、熟悉、熟练掌握、精通），文章版权（原创，转载）。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

可以看看力扣的。https://leetcode-cn.com/

**Comment by fantasticit** [comment]
已增加批量操作。
