### ISSUE TITLE
项目启动后，无法打开admin client页面

### ISSUE THREAD

**Issue by shlroland** [fantasticit/wipi#58]
`@wipi/client: [ info ]  bundled successfully, waiting for typecheck results...`
一直处于这个状态

**Comment by shlroland** [comment]
就next的编译过程特别慢

**Comment by shlroland** [comment]
点击页面切换的时候也特别慢😅

**Comment by fantasticit** [comment]
系统信息：
node 版本：

以上信息，麻烦告知一下。

**Comment by shlroland** [comment]
node 14.16
os: macOS 11.2.1

**Comment by fantasticit** [comment]
可以试一下最新的代码。
PS: 还可以试一下，在 `admin`、`client`、`server` 中分别 `yarn dev` 。
