### ISSUE TITLE
安装报错Unknown database 'root'

### ISSUE THREAD

**Issue by valuex** [fantasticit/wipi#60]
在mysql 中创建数据库报错，请帮忙看看如何解决，谢谢。

`mysql -u root -p root;`

报错：
```
root@17e8a4d5a384:/# mysql -u root -p root;
Enter password:
ERROR 1049 (42000): Unknown database 'root'
```

**Comment by fantasticit** [comment]
> 在mysql 中创建数据库报错，请帮忙看看如何解决，谢谢。
> 
> `mysql -u root -p root;`
> 
> 报错：
> 
> ```
> root@17e8a4d5a384:/# mysql -u root -p root;
> Enter password:
> ERROR 1049 (42000): Unknown database 'root'
> ```

先输入：`mysql -u root -p;` 然后再输入数据库密码。（文档上写错了，我改下。）
