### ISSUE TITLE
yarn dev运行后报错

### ISSUE THREAD

**Issue by AKmoex** [fantasticit/wipi#76]
yarn安装完依赖后，执行yarn dev 运行失败了，打开3000，显示的错误如下所示，能否帮忙看看错误原因以及解决办法
![屏幕截图 2021-06-18 151708](https://user-images.githubusercontent.com/63089888/122522289-5d82ad80-d048-11eb-9030-1ff685518c90.png)

**Comment by fantasticit** [comment]
你贴一下命令行报错信息吧。这个报错信息不够完整，看不出来。。。

**Comment by AKmoex** [comment]
![屏幕截图 2021-06-19 071851](https://user-images.githubusercontent.com/63089888/122623535-096edc00-d0cf-11eb-878f-7f42db972196.png)
![屏幕截图 2021-06-19 071921](https://user-images.githubusercontent.com/63089888/122623542-0ecc2680-d0cf-11eb-97e6-71afa8cd1b0c.png)
![屏幕截图 2021-06-19 072030](https://user-images.githubusercontent.com/63089888/122623552-1b507f00-d0cf-11eb-8dfd-002c718e522d.png)
![屏幕截图 2021-06-19 072107](https://user-images.githubusercontent.com/63089888/122623557-1f7c9c80-d0cf-11eb-9b39-90b802d6ee5b.png)
这是终端的一些输出，client和admin都无法打开，输出信息类似，以前也没遇到过这样的问题

**Comment by fantasticit** [comment]
在 windows 试了下，没能复现。
你可以试下 node14，然后重装依赖，看能不能运行。

**Comment by AKmoex** [comment]
经过一番调试，拉取nextjs官方给的那个小demo的repo，运行后居然出现了一摸一样的错误。
所以这里的问题应该不在本项目，可能是我本地环境或许有点问题。
谢谢你的帮忙，非常感谢！

**Comment by fantasticit** [comment]
太难了，玄学~~ 😭

**Comment by AKmoex** [comment]
在next仓库的discussions中发现也有人遇到这样的问题，经尝试一个可行的解决方案：在vscode中运行yarn dev，跑起来了，真玄学。

**Comment by AKmoex** [comment]
补充：终端中在路径大小写正确的情况下也是可以的，例如改desktop/wipi为Desktop/wipi （windows下）

**Comment by shanwenjie** [comment]
node 16 拉不下来 node-sass,怎么办？
<img width="602" alt="image" src="https://user-images.githubusercontent.com/17475404/159668784-7f4abab0-d899-48fe-b053-a5c57688b482.png">
