### ISSUE TITLE
您好，我启动进入后台的时候进入article时显示报错了

### ISSUE THREAD

**Issue by inspire-lts** [fantasticit/wipi#79]
![image](https://user-images.githubusercontent.com/33800259/123422351-ab6f5680-d5f0-11eb-8c78-7e2e4cd7e429.png)

**Comment by fantasticit** [comment]
fixed.

**Comment by inspire-lts** [comment]
@fantasticit  十分感谢您的开源项目，我最近刚好在学习next。请问一下我怎么能更好的把您的项目看懂，我目前是一个技术栈为react的实习生

**Comment by inspire-lts** [comment]
@fantasticit  十分感谢您的开源项目，我最近刚好在学习next。请问一下我怎么能更好的把您的项目看懂，我目前是一个技术栈为react的实习生

**Comment by fantasticit** [comment]
先看一下 React 文档（https://zh-hans.reactjs.org/docs/getting-started.html）， 然后看一下 next.js 的例子（https://github.com/vercel/next.js/tree/canary/examples）。
