### ISSUE TITLE
server 启动报错

### ISSUE THREAD

**Issue by tilkofjin** [fantasticit/wipi#80]
node环境为 v15.10.0 时启动报错：
![截屏2021-07-02 下午8 45 43](https://user-images.githubusercontent.com/24365622/124279260-dec65e00-db79-11eb-8abe-4fd9f3386bd9.png)
服务端无法正常启动，于是将node环境切到v14.15.1 启动项目，3端都能运行，但仍有报错，admin端新增文章时接口返回500，异常信息如下：
![截屏2021-07-02 下午9 16 18](https://user-images.githubusercontent.com/24365622/124280040-c99dff00-db7a-11eb-829a-65ae1c28d208.png)
非常感谢大佬的开源项目，希望大佬后期出一期 lerna 搭建大型混合工程的视屏教程，大佬的目录结构清晰明了，非常适合全栈开发学习！～

**Comment by fantasticit** [comment]
看起来是数据库格式问题，试下：`CREATE DATABASE  `wipi` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;`？

**Comment by tilkofjin** [comment]
> 看起来是数据库格式问题，试下：`CREATE DATABASE `wipi` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;`？

数据库格式错误导致，感谢！～期待大佬出教程！～
