### ISSUE TITLE
谁来升级成 webpack5  

### ISSUE THREAD

**Issue by shanwenjie** [fantasticit/wipi#89]
这个工程主要是 webpack4 打包，可以用 webpack5 进行升级不？大神帮忙改进下。

**Comment by fantasticit** [comment]
抱歉，现在业余时间的主要用来开发 [云策文档](https://github.com/fantasticit/think)。

[next-template](https://github.com/fantasticit/next-template)

着急的话，可以先看下上面的模板库。
