### ISSUE TITLE
本地运行疑似next报错

### ISSUE THREAD

**Issue by aidoit** [fantasticit/wipi#91]
Warning: render(...): It looks like the React-rendered content of this container was removed without using React. This is not supported and will cause errors. Instead, call ReactDOM.unmountComponentAtNode to empty a container.

**Comment by fantasticit** [comment]
不好意思，项目可能有点过时了，我会在接下来几周的周末逐个升级修复。

**Comment by aidoit** [comment]
没有没有，不过时， 是我有点吹毛求疵了 ，太喜欢这套博客了，本来在看vue，现在主动向react靠拢求虐，继续肝啊。

fantasticit ***@***.***> 于2022年5月5日周四 16:16写道：
