### ISSUE TITLE
主要分支可以运行，pnpm那个弄了半天，没启动成功

### ISSUE THREAD

**Issue by caojwaqzh** [fantasticit/wipi#94]
还有为什么demo里有留言板和关于，项目里启动了就没有了

**Comment by fantasticit** [comment]
1. pnpm 分支要用 pnpm 来安装依赖、启动。这个分支还没收尾，还需要继续开发
2. 留言板和关于属于页面，是在后台配置生成的。本地启动时需要自己在后台新建页面

**Comment by caojwaqzh** [comment]
好的 谢谢 功能很完整 对于刚入门ssr 帮助很大 谢谢
