### ISSUE TITLE
本地启动后 登录时 如果填写错误账号密码 会有这个错 是如果发布后 就不会弹出吗

### ISSUE THREAD

**Issue by caojwaqzh** [fantasticit/wipi#96]
![image](https://user-images.githubusercontent.com/99940383/168942338-31cc3dd3-7607-4770-97b0-f77844a8e505.png)

**Comment by fantasticit** [comment]
前台的登录实现的不好，没有和后台打通。登录只是为了能让评论，登录出错也没关系。我会在 pnpm 分支完善这一块。

**Comment by caojwaqzh** [comment]
好 那个作者问你个事 我想用这个项目给公司弄个技术博客 不知道你同意吗 因为重新自己实现一个 没时间 加上自己对ssr也不是很熟悉 可以吗 我加你一个微信
