### ISSUE TITLE
生产环境部署发生JS内存泄漏

### ISSUE THREAD

**Issue by aidoit** [fantasticit/wipi#97]
![photo_2022-06-01_18-38-17](https://user-images.githubusercontent.com/22998237/171558340-84fe71c0-caeb-4a3f-a84b-d9e3082b1cb3.jpg)
腾讯云轻量 2H2G
按脚本部署的

**Comment by fantasticit** [comment]
本地构建吧

**Comment by aidoit** [comment]
本地环境为WSL:Ubuntu20.x，生产环境为Centos8 Stream，Node版本均安装为14.19.1,npm和yarn 版本均一致
将应用上传后，目前问题是生产环境中client无法和接口通信
![Snipaste_2022-06-05_16-10-09](https://user-images.githubusercontent.com/22998237/172041842-9abc5e13-fe69-48bd-906e-18abfcc13c1c.jpg)
Server端好像仍尝试加载.env文件,没有加载.env.prod

**Comment by fantasticit** [comment]
https://github.com/fantasticit/wipi/tree/refactor/pnpm 

这个分支会轻量点，可以试试。

**Comment by aidoit** [comment]
pnpm分支移除了扫码分享功能，还是喜欢主分支，最近在尝试CI/CD 。
