### ISSUE TITLE
pnpm分支换成主分支了

### ISSUE THREAD

**Issue by aidoit** [fantasticit/wipi#99]
这个轻量版没有二维码分享了。

**Comment by aidoit** [comment]
还有一个问题是，为什么之前的yarn版本 https://blog.wipi.tech/ 
 在生产环境部署，要么在“creating an optimized production build... ” 卡住，
![hang_up](https://user-images.githubusercontent.com/22998237/180255286-d0c0cc8b-2302-43ec-972b-8d6545f6e4da.png)
要么发生内存泄漏。
![heap_out](https://user-images.githubusercontent.com/22998237/180255909-e6ff9554-686d-4ba5-a509-3a53637ed9a1.png)
但pnpm版就不会，是因为node-sass的缘故？还是生产环境内存配置（2G）太小的缘故？
尝试yarn版本使用本地构建后上传，客户端、后台管理、服务端分别出现如下错误：
client：
![client_error](https://user-images.githubusercontent.com/22998237/180256507-57e46c7f-00ad-4225-af46-b9879458f684.png)

admin:
![admin_error](https://user-images.githubusercontent.com/22998237/180256594-9fedf658-539f-4d47-9d45-7c2d577e989a.png)

server:
![server_error](https://user-images.githubusercontent.com/22998237/180256670-b436cedc-bcec-4e84-b53c-b0ccb245672e.png)

还有一个问题：不确定是不是没有在生产环境构建的原因，为文章设置首页聚焦的功能也没有响应。

不好意思，一口气问的问题有点多，但真的是喜欢nextjs，更喜欢这套cms，通过您的源码学到了太多，非常感谢！

**Comment by fantasticit** [comment]
- 二维码：环境依赖比较多，生成方案不太行，先移除，有好的方案再更新
- node-sass：坑点太多了，切到 sass 好了很多
- 功能无响应：需要更多的信息，可能是代码bug
